#!/bin/bash
#PBS -q normal
#PBS -P v45
#PBS -l walltime=24:00:00,mem=192GB
#PBS -l ncpus=48
#PBS -l wd
#PBS -l storage=gdata/hh5+gdata/nm03

module load nco

# num cpus
n=48
# maximum time in hrs (8 days - centre )
zmax=191
# number of z loops
jmax=$[ $zmax/$n + 1 ]

# run 48 collation jobs in parallel
for j in $(seq 0 $jmax)
do
	nstart=$[$n*$j]
	nend=$[$nstart+$n-1]

	if [ $nend -gt $zmax ]
	then
		nend=$tmax
	fi

	for i in $(seq $nstart $nend)
	do
		./concat_one_time $i &
	done

	# wait for the first 48 jobs to finish
	wait

done

# issue single core collation of z levels
qsub qsub_collate_z
